/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecialistsRouteImport } from './routes/specialists'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as CancelRouteImport } from './routes/cancel'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookSpecialistIdRouteImport } from './routes/book.$specialistId'
import { Route as ApiPublicBookingStatusIdRouteImport } from './routes/api/public/booking-status.$id'

const SpecialistsRoute = SpecialistsRouteImport.update({
  id: '/specialists',
  path: '/specialists',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelRoute = CancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSpecialistIdRoute = BookSpecialistIdRouteImport.update({
  id: '/book/$specialistId',
  path: '/book/$specialistId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingStatusIdRoute =
  ApiPublicBookingStatusIdRouteImport.update({
    id: '/api/public/booking-status/$id',
    path: '/api/public/booking-status/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cancel': typeof CancelRoute
  '/confirmation': typeof ConfirmationRoute
  '/specialists': typeof SpecialistsRoute
  '/book/$specialistId': typeof BookSpecialistIdRoute
  '/api/public/booking-status/$id': typeof ApiPublicBookingStatusIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cancel': typeof CancelRoute
  '/confirmation': typeof ConfirmationRoute
  '/specialists': typeof SpecialistsRoute
  '/book/$specialistId': typeof BookSpecialistIdRoute
  '/api/public/booking-status/$id': typeof ApiPublicBookingStatusIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cancel': typeof CancelRoute
  '/confirmation': typeof ConfirmationRoute
  '/specialists': typeof SpecialistsRoute
  '/book/$specialistId': typeof BookSpecialistIdRoute
  '/api/public/booking-status/$id': typeof ApiPublicBookingStatusIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cancel'
    | '/confirmation'
    | '/specialists'
    | '/book/$specialistId'
    | '/api/public/booking-status/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cancel'
    | '/confirmation'
    | '/specialists'
    | '/book/$specialistId'
    | '/api/public/booking-status/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cancel'
    | '/confirmation'
    | '/specialists'
    | '/book/$specialistId'
    | '/api/public/booking-status/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CancelRoute: typeof CancelRoute
  ConfirmationRoute: typeof ConfirmationRoute
  SpecialistsRoute: typeof SpecialistsRoute
  BookSpecialistIdRoute: typeof BookSpecialistIdRoute
  ApiPublicBookingStatusIdRoute: typeof ApiPublicBookingStatusIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/specialists': {
      id: '/specialists'
      path: '/specialists'
      fullPath: '/specialists'
      preLoaderRoute: typeof SpecialistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel': {
      id: '/cancel'
      path: '/cancel'
      fullPath: '/cancel'
      preLoaderRoute: typeof CancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$specialistId': {
      id: '/book/$specialistId'
      path: '/book/$specialistId'
      fullPath: '/book/$specialistId'
      preLoaderRoute: typeof BookSpecialistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking-status/$id': {
      id: '/api/public/booking-status/$id'
      path: '/api/public/booking-status/$id'
      fullPath: '/api/public/booking-status/$id'
      preLoaderRoute: typeof ApiPublicBookingStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CancelRoute: CancelRoute,
  ConfirmationRoute: ConfirmationRoute,
  SpecialistsRoute: SpecialistsRoute,
  BookSpecialistIdRoute: BookSpecialistIdRoute,
  ApiPublicBookingStatusIdRoute: ApiPublicBookingStatusIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
